CREATE DATABASE QUANLIGIAOVU
USE QUANLIGIAOVU

CREATE TABLE KHOA
(
MAKHOA varchar(4) PRIMARY KEY,
TENKHOA varchar(40),
NGTLAP smalldatetime,
TRGKHOA char(4)
)

CREATE TABLE MONHOC
(
MAMH varchar(10) PRIMARY KEY,
TENMH varchar(40),
TCLT tinyint,
TCTH tinyint,
MAKHOA varchar(4) FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE DIEUKIEN
(
MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
MAMH_TRUOC varchar(10),
)

CREATE TABLE GIAOVIEN
(
MAGV char(4) PRIMARY KEY,
HOTEN varchar(40),
HOCVI varchar(10),
HOCHAM varchar(10),
NGSINH smalldatetime,
NGVL smalldatetime,
HESO numeric(4,2),
MUCLUONG money,
MAKHOA varchar(4) FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE LOP
(
MALOP char(3) PRIMARY KEY,
TENLOP varchar(40),
TRGLOP char(5),
SISO tinyint,
MAGVCN char(4)
)

CREATE TABLE HOCVIEN
(
MAHV char(5) PRIMARY KEY,
HO varchar(40),
TEN varchar(10),
NGSINH smalldatetime,
GIOITINH varchar(3),
NOISINH varchar(40),
MALOP char(3) FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)

CREATE TABLE GIANGDAY
(
MALOP char(3) FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
MAGV char(4) FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
HOCKY tinyint,
NAM smallint,
TUNGAY smalldatetime,
DENNGAY smalldatetime
)

CREATE TABLE KETQUATHI
(
MAHV char(5) FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
LANTHI tinyint,
NGTHI smalldatetime,
DIEM numeric(4,2), 
KQUA varchar(10)
)

ALTER TABLE HOCVIEN ADD
GHICHU varchar(40),
DIEMTB float,
XEPLOAI varchar(5)

ALTER TABLE HOCVIEN 
ADD CONSTRAINT CHECK_GT CHECK (GIOITINH IN ('Nam', 'Nu'))

ALTER TABLE KETQUATHI ALTER 
COLUMN DIEM float

UPDATE KETQUATHI
SET KQUA = CASE
WHEN DIEM >= 5 AND DIEM <= 10 THEN 'Dat'
ELSE 'Khong dat'
END;

ALTER TABLE KETQUATHI
ADD CONSTRAINT CHECK_LANTHI CHECK (LANTHI < 4 AND LANTHI >= 0)

ALTER TABLE GIANGDAY
ADD CONSTRAINT CHECK_HOCKY CHECK (HOCKY < 4 AND HOCKY > 0)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHECK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))