USE QUANLIGIAOVU

--II. Ngôn ngữ thao tác dữ liệu (Data Manipulation Language):
--Câu 1
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (
				SELECT TRGKHOA
				FROM KHOA
				)

--Câu 2
UPDATE HOCVIEN
SET DIEMTB = TMP2.DTB
FROM( 
	SELECT KQT.MAHV, AVG(DIEM) AS DTB
	FROM KETQUATHI KQT JOIN(
							SELECT MAHV, MAMH, MAX(LANTHI) AS MAXLANTHI
							FROM KETQUATHI
							GROUP BY MAHV, MAMH
							)AS TMP1
							ON KQT.MAHV = TMP1.MAHV
	GROUP BY KQT.MAHV
	)AS TMP2

--Câu 3
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (
				SELECT MAHV
				FROM KETQUATHI
				WHERE LANTHI = 3 AND DIEM < 5 
				)

--Câu 4
UPDATE HOCVIEN
SET XEPLOAI =  CASE 
					WHEN DIEMTB >= 9 THEN 'XS'
					WHEN DIEMTB >= 8 THEN 'G'
					WHEN DIEMTB >= 6.5 THEN 'K'
					WHEN DIEMTB >=5 THEN 'TB'
					ELSE 'Y'
				END
				
--III. Ngôn ngữ truy vấn dữ liệu:
--Câu 6
SELECT MH.MAMH, TENMH
FROM MONHOC MH
	JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
	JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE HOTEN = 'Tran Tam Thanh' AND HOCKY = 1 AND NAM = 2006


--Câu 7
SELECT MH.MAMH, TENMH
FROM MONHOC MH
	JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
WHERE MAGV = (
			  SELECT MAGVCN
			  FROM LOP
			  WHERE MALOP = 'K11'
			  ) AND HOCKY = 1 AND NAM = 2006

--Câu 8
SELECT HO + TEN AS HOTEN
FROM HOCVIEN
WHERE MAHV IN (
				SELECT DISTINCT TRGLOP
				FROM LOP JOIN GIANGDAY GD ON LOP.MALOP = GD.MALOP
				WHERE MAGV IN (
								SELECT DISTINCT GV.MAGV
								FROM GIAOVIEN GV JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
								WHERE HOTEN = 'Nguyen To Lan' AND MAMH = (SELECT MAMH
																		  FROM MONHOC
																		  WHERE TENMH = 'Co So Du Lieu')
								)
				) 


--Câu 9
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN( 
			  SELECT MAMH_TRUOC
			  FROM DIEUKIEN
			  WHERE MAMH = (
						    SELECT MAMH
						    FROM MONHOC
						    WHERE TENMH = 'Co So Du Lieu'
						   )
			)

--Câu 10
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN(
			  SELECT MAMH
			  FROM DIEUKIEN
			  WHERE MAMH_TRUOC = (
								  SELECT MAMH
								  FROM MONHOC
								  WHERE TENMH = 'Cau Truc Roi Rac'
								  )
			 )
			 
--Câu 11
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN(
			  SELECT MAGV
			  FROM GIANGDAY
			  WHERE MALOP = 'K11' AND HOCKY = 1 AND NAM = 2006 AND MAMH = 'CTRR'
			  INTERSECT
			  SELECT MAGV
			  FROM GIANGDAY
			  WHERE MALOP = 'K12' AND HOCKY = 1 AND NAM = 2006 AND MAMH = 'CTRR'
			  )
		
--Câu 12
SELECT MAHV, HO + TEN AS HOTEN
FROM HOCVIEN
WHERE MAHV IN (
				SELECT MAHV
				FROM (
					  SELECT MAHV, MAX(LANTHI) AS MAXLANTHI
					  FROM KETQUATHI
					  WHERE MAMH = 'CSDL' 
					  GROUP BY MAHV
					 ) AS TMP1
				WHERE MAXLANTHI = 1 
	   INTERSECT 
				SELECT MAHV
				FROM KETQUATHI
				WHERE MAMH = 'CSDL' AND KQUA = 'Khong dat'
				)

--Câu 13
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
				SELECT MAGV
				FROM GIAOVIEN
				EXCEPT
				SELECT DISTINCT MAGV 
				FROM GIANGDAY
				)


--Câu 14
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV NOT IN (
					SELECT GD.MAGV 
					FROM GIANGDAY GD
						 JOIN MONHOC MH ON GD.MAMH = MH.MAMH
						 JOIN GIAOVIEN GV ON GV.MAKHOA = MH.MAKHOA AND GD.MAGV = GV.MAGV
				  )
	  
--Câu 15
SELECT HO + TEN AS HOTEN
FROM HOCVIEN
WHERE MALOP = 'K11' AND MAHV IN (
								SELECT MAHV
								FROM KETQUATHI
								WHERE LANTHI = 3 AND KQUA = 'Khong dat'
								UNION
								SELECT MAHV
								FROM KETQUATHI
								WHERE LANTHI = 2 AND MAMH = 'CTRR' AND DIEM = 5
								)

--Câu 16
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
				SELECT MAGV
				FROM(
						SELECT MAGV, HOCKY, NAM, COUNT(MALOP) AS SLL
						FROM GIANGDAY
						WHERE MAMH = 'CTRR'
						GROUP BY MAGV, HOCKY, NAM
						)AS TMP 
				WHERE SLL >= 2
				)

--Câu 17
SELECT KQT.MAHV, DIEM
FROM (SELECT MAHV, MAX(LANTHI) AS MAXLANTHI
	  FROM KETQUATHI
	  WHERE MAMH = 'CSDL'
	  GROUP BY MAHV) AS TMP
	  JOIN KETQUATHI KQT 
	  ON TMP.MAHV = KQT.MAHV AND KQT.LANTHI = TMP.MAXLANTHI AND KQT.MAMH = 'CSDL'
ORDER BY KQT.MAHV 

--Câu 18
SELECT MAHV, MAXDIEM
FROM (SELECT MAHV, MAX(DIEM) AS MAXDIEM
	  FROM KETQUATHI
	  WHERE MAMH = 'CSDL'
	  GROUP BY MAHV) AS TMP

	  